export const phases = [
  {
    id: "phase-1",
    title: "Phase 1: Foundation (Bulan 1–3)",
    description: "Membangun fondasi infrastruktur dan scripting backend sederhana.",
    goals: "Linux, Bash, Docker, Python, Git",
    project: "python-fastapi-todo",
    tasks: [
      { id: "t1-1", title: "Kuasai Linux Commands & Shell Scripting (Bash)", done: false },
      { id: "t1-2", title: "Paham Konsep Git & Git Flow (Commit, PR, Merge)", done: false },
      { id: "t1-3", title: "Belajar Python Dasar (Variabel, Looping, OOP)", done: false },
      { id: "t1-4", title: "Bikin API sederhana pakai FastAPI (Python)", done: false },
      { id: "t1-5", title: "Belajar Docker (Dockerfile, Docker Compose)", done: false },
      { id: "t1-6", title: "Project: python-fastapi-todo (FastAPI + Docker)", done: false },
    ],
  },
  {
    id: "phase-2",
    title: "Phase 2: Cloud & Node.js (Bulan 4–6)",
    description: "Memasuki dunia Cloud (AWS) dan ekosistem backend terpopuler.",
    goals: "K8s, JavaScript/Node.js, PostgreSQL",
    project: "node-express-todo + k8s-deploy",
    tasks: [
      { id: "t2-1", title: "Belajar JavaScript (ES6, Async/Await)", done: false },
      { id: "t2-2", title: "Bikin API pakai Node.js + Express", done: false },
      { id: "t2-3", title: "Belajar PostgreSQL (Relasi, Query, Indexing)", done: false },
      { id: "t2-4", title: "Konsep Dasar Kubernetes (Minikube, Pods, Services)", done: false },
      { id: "t2-5", title: "Project: node-express-todo (Express + Postgres + JWT)", done: false },
      { id: "t2-6", title: "Lulus Sertifikasi AWS SAA (Solutions Architect Associate) 🏆", done: false },
    ],
  },
  {
    id: "phase-3",
    title: "Phase 3: The SRE Way (Bulan 7–10)",
    description: "Mempelajari bahasa idaman SRE (Go) dan otomatisasi infrastruktur.",
    goals: "Go, Terraform, Ansible, Prometheus",
    project: "go-gin-todo + devops-infra + monitoring",
    tasks: [
      { id: "t3-1", title: "Belajar Golang (Goroutines, Structs, Pointers)", done: false },
      { id: "t3-2", title: "Bikin Backend API super cepat pakai Go (Gin)", done: false },
      { id: "t3-3", title: "Belajar Infrastructure as Code (Terraform) - Bikin VPC EC2", done: false },
      { id: "t3-4", title: "Belajar Configuration Management (Ansible)", done: false },
      { id: "t3-5", title: "Monitoring Stack (Prometheus + Grafana + AlertManager)", done: false },
      { id: "t3-6", title: "Project: devops-infra (Deploy Go app pakai Terraform)", done: false },
    ],
  },
  {
    id: "phase-4",
    title: "Phase 4: Enterprise Ready (Bulan 11–14)",
    description: "Masuk ke ekosistem Enterprise (Java) dan GitOps.",
    goals: "Java/Spring Boot, Kafka, Redis, ArgoCD",
    project: "java-springboot-todo + k8s-gitops",
    tasks: [
      { id: "t4-1", title: "Belajar Java Dasar & OOP Lanjutan", done: false },
      { id: "t4-2", title: "Bikin Backend pakai Java Spring Boot", done: false },
      { id: "t4-3", title: "Belajar Message Broker (Apache Kafka)", done: false },
      { id: "t4-4", title: "Belajar Caching (Redis)", done: false },
      { id: "t4-5", title: "Belajar GitOps (Helm Charts + ArgoCD)", done: false },
      { id: "t4-6", title: "Project: k8s-gitops (Deploy Spring Boot pakai ArgoCD)", done: false },
      { id: "t4-7", title: "Mulai Lamar kerja posisi Junior SRE / DevOps 🏆", done: false },
    ],
  },
  {
    id: "phase-5",
    title: "Phase 5: Microservices (Bulan 15–20)",
    description: "Menggabungkan semuanya menjadi sistem skala besar.",
    goals: "Microservices, System Design, CI/CD",
    project: "microservices-polyglot",
    tasks: [
      { id: "t5-1", title: "Paham Konsep Microservices vs Monolith", done: false },
      { id: "t5-2", title: "Belajar CI/CD Pipeline (GitLab CI / GitHub Actions)", done: false },
      { id: "t5-3", title: "Belajar NGINX / API Gateway", done: false },
      { id: "t5-4", title: "Project: microservices-polyglot (Gabung Go, Java, Python, Node)", done: false },
      { id: "t5-5", title: "Mulai Lamar kerja posisi Backend Engineer 🏆", done: false },
    ],
  },
];
